// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Siem.Api.Data;

#nullable disable

namespace Siem.Api.Data.Migrations
{
    [DbContext(typeof(SiemDbContext))]
    [Migration("20260326022601_FixAgentRiskSummaryFunction")]
    partial class FixAgentRiskSummaryFunction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Siem.Api.Data.Entities.AgentActivityHourlyView", b =>
                {
                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_name");

                    b.Property<double?>("AvgLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_latency_ms");

                    b.Property<DateTime>("Bucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket");

                    b.Property<long>("EventCount")
                        .HasColumnType("bigint")
                        .HasColumnName("event_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<double?>("MaxLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("max_latency_ms");

                    b.Property<double?>("P95LatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("p95_latency_ms");

                    b.Property<long?>("TotalInputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_input_tokens");

                    b.Property<long?>("TotalOutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_output_tokens");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_tokens");

                    b.Property<long>("UniqueSessionsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("unique_sessions");

                    b.Property<long>("UniqueToolsUsed")
                        .HasColumnType("bigint")
                        .HasColumnName("unique_tools_used");

                    b.ToTable((string)null);

                    b.ToView("agent_activity_hourly", (string)null);
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.AgentEventReadModel", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_name");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<long?>("KafkaOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("kafka_offset");

                    b.Property<short?>("KafkaPartition")
                        .HasColumnType("smallint")
                        .HasColumnName("kafka_partition");

                    b.Property<double?>("LatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ModelId")
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("SeverityHint")
                        .HasColumnType("text")
                        .HasColumnName("severity_hint");

                    b.Property<string>("SourceSdk")
                        .HasColumnType("text")
                        .HasColumnName("source_sdk");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("ToolInput")
                        .HasColumnType("text")
                        .HasColumnName("tool_input");

                    b.Property<string>("ToolName")
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.Property<string>("ToolOutput")
                        .HasColumnType("text")
                        .HasColumnName("tool_output");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.HasKey("EventId");

                    b.ToTable("agent_events", (string)null);
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.AgentRiskSummary", b =>
                {
                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_name");

                    b.Property<double>("AvgLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_latency_ms");

                    b.Property<long>("CriticalAlerts")
                        .HasColumnType("bigint")
                        .HasColumnName("critical_alerts");

                    b.Property<double>("EventsPerMinute")
                        .HasColumnType("double precision")
                        .HasColumnName("events_per_minute");

                    b.Property<long>("OpenAlerts")
                        .HasColumnType("bigint")
                        .HasColumnName("open_alerts");

                    b.Property<string>("TopEventTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("top_event_types");

                    b.Property<string>("TopTools")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("top_tools");

                    b.Property<long>("TotalEvents")
                        .HasColumnType("bigint")
                        .HasColumnName("total_events");

                    b.Property<long>("TotalSessions")
                        .HasColumnType("bigint")
                        .HasColumnName("total_sessions");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_tokens");

                    b.Property<long>("UniqueTools")
                        .HasColumnType("bigint")
                        .HasColumnName("unique_tools");

                    b.ToTable("AgentRiskSummaries");
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.AgentSessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_name");

                    b.Property<short>("AlertCount")
                        .HasColumnType("smallint")
                        .HasColumnName("alert_count");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer")
                        .HasColumnName("event_count");

                    b.Property<bool>("HasAlerts")
                        .HasColumnType("boolean")
                        .HasColumnName("has_alerts");

                    b.Property<DateTime>("LastEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at");

                    b.Property<string>("MaxSeverity")
                        .HasColumnType("text")
                        .HasColumnName("max_severity");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("SessionId");

                    b.ToTable("agent_sessions", (string)null);
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.AlertEntity", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text")
                        .HasColumnName("assigned_to");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("Suppressed")
                        .HasColumnType("boolean")
                        .HasColumnName("suppressed");

                    b.Property<Guid?>("SuppressedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("suppressed_by");

                    b.Property<DateTime?>("SuppressionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suppression_expires_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.HasKey("AlertId");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.AlertEventEntity", b =>
                {
                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp");

                    b.Property<short?>("SequenceOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence_order");

                    b.HasKey("AlertId", "EventId");

                    b.ToTable("alert_events", (string)null);
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.ListMemberEntity", b =>
                {
                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("ListId", "Value");

                    b.ToTable("managed_list_members", (string)null);
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.ManagedListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("managed_lists", (string)null);
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.RuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("actions_json");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("condition_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("EvaluationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evaluation_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SequenceConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("sequence_config");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TemporalConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("temporal_config");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.SessionTimelineEntry", b =>
                {
                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.PrimitiveCollection<Guid[]>("AlertIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("alert_ids");

                    b.PrimitiveCollection<string[]>("AlertSeverities")
                        .HasColumnType("text[]")
                        .HasColumnName("alert_severities");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<double?>("LatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ModelId")
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("ToolName")
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.ToTable("SessionTimelineEntries");
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.SuppressionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.HasKey("Id");

                    b.ToTable("suppressions", (string)null);
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.ToolUsageHourlyView", b =>
                {
                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<double?>("AvgLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_latency_ms");

                    b.Property<DateTime>("Bucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket");

                    b.Property<long>("InvocationCount")
                        .HasColumnType("bigint")
                        .HasColumnName("invocation_count");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.Property<long>("UniqueSessions")
                        .HasColumnType("bigint")
                        .HasColumnName("unique_sessions");

                    b.ToTable((string)null);

                    b.ToView("tool_usage_hourly", (string)null);
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.AlertEventEntity", b =>
                {
                    b.HasOne("Siem.Api.Data.Entities.AlertEntity", "Alert")
                        .WithMany("AlertEvents")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.ListMemberEntity", b =>
                {
                    b.HasOne("Siem.Api.Data.Entities.ManagedListEntity", "List")
                        .WithMany("Members")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.AlertEntity", b =>
                {
                    b.Navigation("AlertEvents");
                });

            modelBuilder.Entity("Siem.Api.Data.Entities.ManagedListEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
